Docs(VOCABOLARIO)/addnewwords
riccardogenova/Il-manuale-del-rookie-dev pull request #139
Opened 2023-12-03 15:48 UTC by Maxnohiken

## Descrizione

_Per favore, includi un riepilogo delle modifiche e dei problemi risolti_

## Domande/commenti per il revisore

_Per favore, indica se ci sono cose di cui essere consapevoli o di cui hai bisogno di input_

## Tipo di modifica - seleziona il tipo di modifica pertinente:

- [ ] 🐛 Risoluzione di bug (modifica non critica che risolve un problema)
- [ ] 🆕 Nuova funzionalità (modifica non critica che aggiunge funzionalità)
- [ ] 💄 Regolazione (regolazione visuale o semplici aggiustamenti logici)
- [ ] 💥 Modifica critica (correzioni o funzionalità che potrebbero causare problemi alle esistenti)

## Testato su - seleziona il tipo di dispositivo pertinente:

- [ ] Chrome
- [ ] Firefox
- [ ] Brave

## Come testare - includi un elenco di cose da testare

_Includi collegamenti o altri modi per individuare facilmente i dati di test_

### Screenshots, registrazioni video 📸 👇

_Includi un video in formato GIF. Per Mac puoi utilizzare [GetKap](https://getkap.co/)_

2023-12-11 21:26 UTC, riccardogenova requested changes

2023-12-11 21:26 UTC, riccardogenova commented on helpers/GIT-SHEET.md
> -- `git clone url_repository`: Clona un repository Git esistente nella tua directory locale.
perché è stato rimosso ?

2023-12-11 21:26 UTC, riccardogenova commented on helpers/VOCABOLARIO.md
> +>>>>>>> c308372 (docs(keywordsmd))
qualcosa è andato storto nel rebase ?

2023-12-13 21:50 UTC, closed without merging

2023-12-13 21:51 UTC, Maxnohiken commented on helpers/GIT-SHEET.md
> -- `git clone url_repository`: Clona un repository Git esistente nella tua directory locale.
Al momento della modifica si ripeteva per due volte